server:
  port: 8080

spring:
  application.name: ecommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hh_plus?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: password
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
      pool-name: hh-plus-local

logging:
  slack:
    webhook-url: https://hooks.slack.com/services/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
  config: classpath:logback-spring.xml
  level:
    org:
      springframework:
        transaction:
          interceptor: trace
    root: debug